site_name: Allan Augusto | Data Engineering & DBA
site_url: https://Allanao88.github.io/portfolio-docs/
site_description: Portefólio Técnico de Engenharia de Dados, Infraestrutura e ITSM

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  font:
    text: Roboto
    code: Fira Code

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Allanao88
      name: Allan no GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/allan-augusto-carvalho-de-oliveira-102b985b
      name: Allan no LinkedIn

nav:
  - Início: index.md
  - Engenharia & Projetos:
    - Observabilidade DBA e IA: projetos/portal-monitorizacao
    - Arquitetura Apache Airflow: projetos/airflow-observabilidade
  - DBA & Operações:
    - Resiliência e RCA: dba/resiliencia-rca
    - Scripts e Automações: dba/scripts
  - Gestão & ITSM:
    - Automação Corporativa (Bitrix24): crm/bitrix24
    - Service Desk & SLAs (GLPI): crm/glpi
